name: MinimaxMenuMonitor
options:
  bundleIdPrefix: com.minimaxmenu
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  buildDir: build

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  MinimaxMenuMonitor:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources
        type: group
      - path: Resources
        type: group
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.minimaxmenu.MinimaxMenuMonitor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
        CONFIGURATION_BUILD_DIR: $(SRCROOT)/build/$(CONFIGURATION)
